### ISSUE TITLE
Rotating screen in details doesn't restore the toolbar.

### ISSUE THREAD

**Issue by quinnjn** [derekcsm/hubble_gallery#3]
Rotating in the details causes the toolbar to do some weird stuff. I assume it's not being restored. Upon scrolling it corrects itself. 

Included a screenshot of what happens. Scrolling causes it to restore alpha and colour.

![image](https://cloud.githubusercontent.com/assets/1859215/7994042/97cf0ecc-0ac7-11e5-8fe0-f48912fda9c2.png)

**Comment by derekcsm** [comment]
Nice find! thanks, probably something screwy in FragDetails instance state

**Comment by derekcsm** [comment]
Fixed this, now in 1.0.1 branch It'll be out in the next release.
