### ISSUE TITLE
Cannot connect: "No internet connection"

### ISSUE THREAD

**Issue by davidhedlund** [derekcsm/hubble_gallery#52]
Hubble Gallery cannot connect to internet, I get message "No internet connection", but all other apps that I use can connect.

**Comment by jacksgt** [comment]
I can confirm this issue on Android 7.1.2, App version 1.5.0 (from F-Droid).
![screenshot-hubble](https://user-images.githubusercontent.com/11589682/28353743-68999984-6c5d-11e7-9ad1-9800748e9c09.png)

**Comment by ZeFenX** [comment]
I have the same issue on 7.1.1 with 1.5.0 app from F-Droid.

**Comment by teunbruijnen** [comment]
Same, saw on twitter that some change to /gallery messed up the code, and derek sent a message to inquire. That's all I've seen on the issue, tweet was 8 months ago.

**Comment by jeyca** [comment]
same issue on lineage OS 14.1 ...

**Comment by IzzySoft** [comment]
@derekcsm I vaguely remember there was something with site changes (where you pick up the images). Are you going to fix that – or are you declaring the app "unmaintained"? Because in the latter case, we had to remove the app from the F-Droid main repo (and move it to archive, which [was already requested](https://gitlab.com/fdroid/fdroiddata/merge_requests/5181)). Would be good to hear from you before we're taking action.

**Comment by IzzySoft** [comment]
@derekcsm any word – or must we simply assume this project has been abandoned? In that case we'd archive the app. That means, it would no longer be visible in the main repo, but only in Archive. We can move it back to main once you're supplying a new version and we can build that – so an answer along the lines "no time currently but might pickup later" would perfectly fit that strategy.

**Comment by jacksgt** [comment]
Considering that the last commit to this repository was in December 2016 (3 years ago) and that the original author is not responding to any issue, I think we have to consider this project abandoned.

**Comment by derekcsm** [comment]
Yeah it's abandoned unfortunately, if someone wants to take up the challenge to rebuild this or a whole new app I'd be available to give some advice but personally I'm not invested enough to keep this project going. Will add a deprecated title to avoid future confusion.

**Comment by IzzySoft** [comment]
Thanks for the clear words, @derekcsm – I've added a corresponding not to the app's description at F-Droid (should become visible with the next index update), pointing here.
